services:
  discord-bot:
    build: .
    container_name: my-discord-bot
    restart: always
    env_file:
      - .env
    environment:
      - TZ=Asia/Taipei
    volumes:
      - .:/usr/src/app
      - ../resource_transfer:/usr/src/app/resource_transfer
      - /usr/src/app/node_modules
    network_mode: "bridge"